solr_fusion.settings:
  type: config_object
  label: 'Settings for Solr Fusion'
  mapping:
    omit_header:
      type: boolean
      label: 'Should the response header be omitted?'
    debug_mode:
      type: boolean
      label: 'Debug Mode'
